### ISSUE TITLE
Error when calling require in node.js

### ISSUE THREAD

**Issue by ofershap** [arc298/tiktok-captcha-solver#3]
I've added this line to my node.js project:
const CaptchaSolver = require('tiktok-captcha-solver');

And when I'm running I get this error:

```
/node_modules/tiktok-captcha-solver/src/CaptchaSolver.js:6
  options
  ^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/ofershap/my_projecg/node_modules/tiktok-captcha-solver/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by andreconghau** [comment]
I also have met it as above.
What's wrong something @@
